---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: borealis
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # You can pin to a specific version of Fedora as well

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo 
      copr:
        - atim/starship
        - lilay/topgrade
      keys:
        - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    install:
      packages:
        - repo: brave-browser
          packages:
            - brave-origin
        - micro
        - starship
        - liberation-fonts
        - kde-connect
        - clinfo
        - pocl
        - mesa-libOpenCL
        - topgrade
    group-install:
      with-optional: true # install optional packages from group
      packages:
        - cosmic-desktop 
        - development-tools
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - cosmic-store
        - cosmic-player
        - fedora-flathub-remote

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.gnome.Loupe  
          - io.github.diegopvlk.Cine
          - eu.betterbird.Betterbird
          - org.gnome.TextEditor
          - io.github.kolunmi.Bazaar
          - io.github.flattool.Warehouse
          - com.github.tchx84.Flatseal
    
  - type: brew
    auto-update: true
    auto-upgrade: true
    brew-analytics: true

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
